### ISSUE TITLE
Wrong increment of position in EEPROM_Write function

### ISSUE THREAD

**Issue by blopblopblup** [controllerstech/STM32#1]
I have tested the library and all seems great except for one issue I found.
In the EEPROM_Write function, the position of the data buffer is updated for each page as such : 
`pos = bytesremaining;  // update the position for the data buffer`
The issue is for example we write a 48 bytes array in the first address of the first page of a EEPROM with 16 bytes long pages.
At the first page pos=0, all is fine. At the second page pos =16, still fine. At the third page pos=16, oops. 
The solution I found was to update pos like so : 
`pos += bytesremaining;  // update the position for the data buffer`
This way the position variable is updated correctly through the pages.

**Comment by controllerstech** [comment]
Thanks for the update. I think I messed up file before upload, because It would never work with the current setup. 
I will fix it.

**Comment by blopblopblup** [comment]
By the way, there might be a similar issue with the EEPROM_Read function.

**Comment by controllerstech** [comment]
yes I am going to test the entire code again..
